apiVersion: "v1"
kind: "RoleBinding"
metadata:
  name: "fuse-sb-rhdg-quickstart-s2i-7"
roleRef:
  # Add the view role to the service account
  name: "view"
subjects:
  - kind: "ServiceAccount"
    name: "fuse-sb-rhdg-quickstart-s2i-7"
